FROM node:22-alpine

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN apt update && apt install gnupg wget -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
  apt update && \
  apt install google-chrome-stable -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*

ARG PORT=9010

ENV NODE_ENV development

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

RUN npm i -g pm2

COPY package*.json process.yml ./

RUN npm ci

COPY  . .

EXPOSE ${PORT}

ENTRYPOINT ["pm2","start", "./process.yml","--no-daemon"] 