version: "3.3"

services:
  onestoptestnode:
    build:
      context: .
      dockerfile: Dockerfile.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./public:/home/node/app/public
      - onestopimages:/home/node/app/images_folder
      - onestopfiles:/home/node/app/files_folder
    ports:
      - "9035:9010"
    env_file:
      - .env

volumes:
  onestopimages:
  onestopfiles:
