export default {
    MESS: "mess",
    MEDICAL: "medical",
    FOODOUTLET: "food outlet",
    TRANSPORTTIMING: "transport",
    CABSHARING: "cab sharing",
    ONESTOPUSER: "user",
    LOST: "lost",
    FOUND: "found",
    BUY: "buy",
    SELL: "sell",
    CONTACTS: "contacts",
    ANNOUNCEMENT: "announcement",
    SUPERADMIN: "super-admin",
};